data:
  labeled_df_filename: /content/dataset/train.tsv
  unlabeled_df_filename: /content/dataset/test.tsv
  train_size: 0.9
  val_size: 0.1

model:
  model_name: DeepPavlov/rubert-base-cased-sentence
  max_seq_length: 32                   
  num_classes: 2
  dropout: 0.25

training:
  learning_rate: 3e-5                  
  adam_epsilon: 1e-8                   
  num_epochs: 20                         
  batch_size: 16                         

general:
  seed: 42                            
  
  